var myNum;
myNum = 1;
console.log(myNum);
var myString;
myString = "hello";
console.log(myString);
var myBoolean;
myBoolean = true;
console.log(myBoolean);
var myAnyType;
myAnyType = "type any";
console.log(myAnyType);
var arrStr;
arrStr = ["type any", "123"];
console.log(myAnyType);
var arrNum;
arrNum = [1, 2, 3, 4];
console.log(arrNum);
var num;
num = 1;
console.log(num);
var nihal = "superstar";
console.log(nihal);
