"use strict";
let myNum;
myNum = 1;
console.log(myNum);
let myString;
myString = "hello";
console.log(myString);
let myBoolean;
myBoolean = true;
console.log(myBoolean);
let myAnyType;
myAnyType = "type any";
console.log(myAnyType);
let arrStr;
arrStr = ["type any", "123"];
console.log(myAnyType);
let arrNum;
arrNum = [1, 2, 3, 4];
console.log(arrNum);
let num;
num = 1;
console.log(num);
let nihal = "superstar";
console.log(nihal);
